class AddIdentifiers < ActiveRecord::Migration[5.0]
  def change
    add_column :advocacy_campaigns, :identifiers, :text, array: true, default: []
    add_column :answers, :identifiers, :text, array: true, default: []
    add_column :canvasses, :identifiers, :text, array: true, default: []
    add_column :canvassing_efforts, :identifiers, :text, array: true, default: []
    add_column :donations, :identifiers, :text, array: true, default: []
    add_column :events, :identifiers, :text, array: true, default: []
    add_column :forms, :identifiers, :text, array: true, default: []
    add_column :fundraising_pages, :identifiers, :text, array: true, default: []
    add_column :outreaches, :identifiers, :text, array: true, default: []
    add_column :petitions, :identifiers, :text, array: true, default: []
    add_column :queries, :identifiers, :text, array: true, default: []
    add_column :questions, :identifiers, :text, array: true, default: []
    add_column :scripts, :identifiers, :text, array: true, default: []
    add_column :script_questions, :identifiers, :text, array: true, default: []
    add_column :share_pages, :identifiers, :text, array: true, default: []
    add_column :signatures, :identifiers, :text, array: true, default: []
    add_column :submissions, :identifiers, :text, array: true, default: []
  end
end
