export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENT  = 'FETCH_EVENT';

export const FETCH_ATTENDANCES = 'FETCH_ATTENDANCES';
export const UPDATE_ATTENDANCE = 'UPDATE_ATTENDANCE';
export const SET_ATTENDANCE_ATTRIBUTE = 'SET_ATTENDANCE_ATTRIBUTE';
export const ATTENDANCE_CREATE_SUCCESS = 'ATTENDANCE_CREATE_SUCCESS';
export const ATTENDANCE_CREATE_FAIL = 'ATTENDANCE_CREATE_FAIL';
export const CLEAN_ATTENDANCE_ALERTS = 'CLEAN_ATTENDANCE_ALERTS';

export const FETCH_GROUPS = 'FETCH_GROUPS';
export const FETCH_GROUP = 'FETCH_GROUP';

export const FETCH_MEMBERS = 'FETCH_MEMBERS';
export const FETCH_MEMBER = 'FETCH_MEMBER';
export const LOOK_UP_MEMBER = 'LOOK_UP_MEMBER';
