export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENT  = 'FETCH_EVENT';
export const FETCH_ATTENDANCES = 'FETCH_ATTENDANCES';
export const UPDATE_ATTENDANCE = 'UPDATE_ATTENDANCE';
export const FETCH_GROUPS = 'FETCH_GROUPS';
export const FETCH_GROUP = 'FETCH_GROUP';
export const FETCH_MEMBERS = 'FETCH_MEMBERS';
