export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENT  = 'FETCH_EVENT';
export const FETCH_ATTENDANCES = 'FETCH_ATTENDANCES';
export const UPDATE_ATTENDANCE = 'UPDATE_ATTENDANCE';
export const FETCH_GROUPS = 'FETCH_GROUPS';
export const FETCH_GROUP = 'FETCH_GROUP';

export const FETCH_MEMBERS = 'FETCH_MEMBERS';
export const FETCH_MEMBER = 'FETCH_MEMBER';
export const CREATE_MEMBER = 'CREATE_MEMBER';
export const LOOK_UP_MEMBER = 'LOOK_UP_MEMBER';
export const SET_MEMBER_ATTRIBUTE = 'SET_MEMBER_ATTRIBUTE';
